version: '3.8'

services: 
  postgres:
    image: postgres:latest
    container_name: property_postgres
    environment:
      POSTGRES_DB: property_listings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    networks:
      - property_network

  redis:
    image: redis:latest
    container_name: property_redis
    ports:
      - "6380:6379"
    volumes:  # <-- Fix spelling: 'volume' ➜ 'volumes'
      - redis_data:/data
    networks:
      - property_network

volumes:
  postgres_data:
  redis_data:

networks:
  property_network:
    driver: bridge
  # This network allows communication between the services
  # and can be used to scale the application if needed.